#if you take any varible arguments/command line will come 1st
- name: variables to print
  hosts: web
  tasks: 
  - name: print the information
    ansible.builtin.debug:
      msg: "Hello {{NAME}}, good {{GREETING}}"

