#check the is user is exit or noy in my_expence
- name: create user
  hosts: web
  become: yes #root user access
  tasks:
  - name: check the user is exit or not
    ansible.builtin.command: id expense
    register: USER #here USER is a variable that get ouput from above command
    ignore_errors: true

  - name: print the user information
    ansible.builtin.debug: 
      msg: "user info: {{USER}}"

  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0 #rc= return  code
  