#how you will install nginx 
- name: install nginx
  hosts: web  
  become: yes
  tasks:
  - name: print the stats
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: install nginx in redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "Redhat"

  - name: install nginx in Debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"

