#install and remove some packages 
- name: loops
  hosts: web
  become: yes
  tasks:
  - name: install packages 
    ansible.builtin.packages:
      name: " {{ iteam.name }}"
      state: "{{ iteam.state }}"
    loop:
    - { name: 'mysql', state: 'present' }
    - { name: 'nginx', state: 'present' }
    - { name: 'postfix', state: 'absent' }
    - { name: 'httpd', state: 'absent' }
    
