- name: command  vs shell
  hosts: local
  connection: local
  tasks:
  - name: execute command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: check the process # login to the server and executes command
    ansible.builtin.shell: ps -ef | grep ssh
    register: output

   - name: check the process # command module just issues the command
    ansible.builtin.command: ps -ef | grep ssh
    register: output
    