#How to create ec2 instance subnets security groups
- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-02adc7d5d94cd7a07 # go to networking nad subnet id
    sg_id: "sg-0e914dc599cdf119a" #go to secqurits group and select secqurity id
    ami_id: "ami-09c813fb71547fc4f" # go to details  ans select ami_id
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instance 
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances}}"

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2-instance }}"



