
- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-02adc7d5d94cd7a07
    sg_id: "sg-0e914dc599cdf119a"
    ami_id: "ami-09c813fb71547fc4f"
    Instances:
    - mysql
    - backend
    - front end
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ iteam }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loops: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"  


